name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.cache/runelite
          key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml', '**/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./ci/build.sh
        
      - name: Checksum Client Build
        run: echo RuneLite.jar `sha256sum /home/runner/work/runelite-but-you-can-save-your-password/runelite-but-you-can-save-your-password/runelite-client/target/*-shaded.jar | cut -d' ' -f1` 
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: RuneLite.jar
          path: /home/runner/work/runelite-but-you-can-save-your-password/runelite-but-you-can-save-your-password/runelite-client/target/*-shaded.jar
          
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          files: /home/runner/work/runelite-but-you-can-save-your-password/runelite-but-you-can-save-your-password/runelite-client/target/*-shaded.jar
